### ISSUE TITLE
 Support day

### ISSUE THREAD

**Issue by cristian-marisescu** [eakmanrq/sqlframe#101]
Hi,

Seems the day function is still unsupported. Could you add it to the list?
https://github.com/eakmanrq/sqlframe/blob/main/sqlframe/base/functions.py#L2166
Thank you in advance!

**Comment by eakmanrq** [comment]
Thanks for reporting this. In order to properly support it I had to finally add full type detection support which is great to finally have it. Will enable more functions/improve many existing functions so excited to have it implemented.
