### ISSUE TITLE
Is the Pandas dependency necessary for all engines?

### ISSUE THREAD

**Issue by datajoely** [eakmanrq/sqlframe#12]
Super cool work - very exciting project between this and [Ibis](https://ibis-project.org/) I'm so excited about the future of composable, flexible systems where syntax is decoupled from execution. 

I noticed in your [setup.py](https://github.com/eakmanrq/sqlframe/blob/9df55e167dc8b4c7f0ba7a4775a7edd67ecb125e/setup.py#L57) that pandas is a required dependency for every back-end. Thinking out loud - I get why you need this to match the Spark API 1:1. 

It's no a massive footprint these days, I think the risk is more for older brownfield projects that have complicated existing dependencies. Part of the appeal for this project is that existing Spark codebases can migrate to say duckdb without any pain, this may crop up over time.

`pip-compile` on pandas with no extras returns the following, the footprint doesn't look super risky, but conflicts may crop up:

```shell
❯ uv pip compile requirements.txt
Resolved 6 packages in 9ms
# This file was autogenerated by uv via the following command:
#    uv pip compile requirements.txt
numpy==1.26.4
    # via pandas
pandas==2.2.2
python-dateutil==2.9.0.post0
    # via pandas
pytz==2024.1
    # via pandas
six==1.16.0
    # via python-dateutil
tzdata==2024.1
    # via pandas
```

**Comment by eakmanrq** [comment]
Yeah only some operations actually require pandas. So I could localize those imports and then tell the user to install pandas to use those functions. Obviously that introduces some friction though. So it is a tradeoff here between the gain of minimizing the required dependencies and lowering friction for users.

**Comment by datajoely** [comment]
Yeah it's not something that you need to worry about today, but it would be great later down the line. Thanks again for the fantastic work I'm already 90% of the way done building a [Kedro](https://github.com/kedro-org/kedro) dataset for it sqlframe 💪

**Comment by datajoely** [comment]
In case you're interested here is my Kedro implementation 
https://github.com/kedro-org/kedro-plugins/pull/694

**Comment by eakmanrq** [comment]
Very cool thanks for sharing! 🙌
