### ISSUE TITLE
Extract column-level lineage

### ISSUE THREAD

**Issue by zhibor** [eakmanrq/sqlframe#138]
Can it support the extraction and visualization of column-level lineage information? It would be super useful for understanding data origins and transformations, along with many other benefits.

**Comment by eakmanrq** [comment]
Thanks for the suggestion @zhibor! I added support for what SQLGlot supports out of the box today. What this means is you need to get CLL for a specific column at a time and you get get the HTML for that column. 

Let me know how much this helps in addressing your use case. Likely adding more support would involve improving SQLGlot itself but happy to hear what thoughts you have to see what would be a good fit.

**Comment by djouallah** [comment]
can you show an example how it works, I am not very familiar with SQLGlot  ?

**Comment by eakmanrq** [comment]
Sorry for missing this at first @djouallah. 

So you would do something like this:
```
df.lineage("year").to_html()
```

Where `df` is your SQLFrame DataFrame and `year` is what you want column-level lineage for. `to_html` converts the node into an HTML representation. If you do this in a notebook it _should_ display the graph below the cell or you could write this to file and then open the file with your browser.

As I noted in the comments, this isn't very user friendly but it is what comes out of the box from SQLGlot.
