### ISSUE TITLE
Feature Request : use .record_batch() for .toArrow()

### ISSUE THREAD

**Issue by djouallah** [eakmanrq/sqlframe#152]
I am running sqlframe in an environment with low memory, I notice that .toArrow()  materialize the whole data in memory, it will useful if instead, if it is translated to  .record_batch() from duckdb, which works in batch

**Comment by eakmanrq** [comment]
Great idea @djouallah! Addressed in this PR: https://github.com/eakmanrq/sqlframe/pull/153
