### ISSUE TITLE
Databricks support

### ISSUE THREAD

**Issue by zerodarkzone** [eakmanrq/sqlframe#202]
I know it sounds weird to support Databricks because you can execute spark code directly on databricks. But it would be Nice to be able to use a Databricks SQL Warehouse with pyspark code.

**Comment by eakmanrq** [comment]
Thanks for the request. Would this ideally use the Python SQL Connector from Databricks? https://docs.databricks.com/en/dev-tools/python-sql-connector.html#language-SQL%C2%A0warehouse

**Comment by zerodarkzone** [comment]
Hi,
Yes. I think that would be a good way to do it.

**Comment by zerodarkzone** [comment]
This is addressed by https://github.com/eakmanrq/sqlframe/pull/207
