### ISSUE TITLE
please provide public base class for sqlframe dataframes

### ISSUE THREAD

**Issue by MarcoGorelli** [eakmanrq/sqlframe#231]
Currently, if I have an object, I can check if it's a sqlframe dataframe by doing `isinstance(df, sqlframe.base.dataframe._BaseDataFrame)`. This works, but it's a private class - any chance a public class (or a public function) could be provided to check if an object is of any sqlframe kind?

use case: sqlframe support in Narwhals

**Comment by eakmanrq** [comment]
Yeah I will just make it public.
