### ISSUE TITLE
Does this library support python udfs?

### ISSUE THREAD

**Issue by jtalmi** [eakmanrq/sqlframe#24]

**Comment by eakmanrq** [comment]
Not currently but this is something I am looking to add support for assuming the target engine supports Python UDFs. What engine are you looking to use a Python UDF with?

**Comment by jtalmi** [comment]
BQ...so I didn't think it was possible...

**Comment by eakmanrq** [comment]
Yeah sadly that would not be possible since BQ doesn't support Python UDFs. 😞

**Comment by eakmanrq** [comment]
If someone has an engine they want to see Python UDF support for please open a new issue with the engine included
